name: Gatsby Publish - Develop

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run deploy
      - run: aws cloudfront create-invalidation --distribution-id E290A7U35T5BSI --paths "/*"
